### ISSUE TITLE
Pressing modifier keys will release currently active keybinds

### ISSUE THREAD

**Issue by Tellinq** [Polyfrost/OneConfig#509]
### Category

Backend, Keybinds

### Bug description

If a current keybind is in a state that it is pressed, pressing any modifier keys such as CTRL, ALT, SHIFT, etc. will cause any keybinds that are currently pressed and have already been triggered to be in a released state.

### Steps to reproduce

One way to reproduce this issue is to use my [Freelook](https://github.com/Tellinq/Freelook) mod (with the config set to Quick Press or Hold) and **hold** the keybind (which is defaulted to F), then press any modifier key.

### Anything else?

Regardless if this is intentional or not, keybinds that have already been activated should not be influenced in triggering another pressed action. Keybinds should only be considered in a released state **only if** at least one of the pressed keys that meet the criteria to trigger the key in the first place has been released.

I am going to ask that my Freelook mod is part of the testing procedure to ensure this issue is resolved. I have reported previous iterations of this being an issue for different reasons in the OneConfig Discord, and none have indicated that my mod was used for testing when I asked how previous resolve attempts have been tested.

**Comment by Tellinq** [comment]
I am still able to reproduce this on alpha.123. Could this please be reopened? How are you verifying this is fixed?

> I am going to ask that my Freelook mod is part of the testing procedure to ensure this issue is resolved. I have reported previous iterations of this being an issue for different reasons in the OneConfig Discord, and none have indicated that my mod was used for testing when I asked how previous resolve attempts have been tested.

When you are testing your fix, are you even able to have OneConfig built with your local PolyUI development build? Additionally are you able to bootstrap this into a mod that would let you test your changes? I'd really like actual comment on how you're testing these changes rather than pushing a commit to a master branch, assuming it's fixed and closing an issue without verifying on the other side (that being me in this case) that this issue is truly resolved.

**Comment by nextdayy** [comment]
try updating to polyui 1.12.1

**Comment by Wyvest** [comment]
> try updating to polyui 1.12.1

alpha.123 is on that polyui version. i can test on my machine to confirm this is still happening if necessary

**Comment by nextdayy** [comment]
i'm fairly sure the reason why this is still broken is that I only tested it on 1.8.9 and it's probably broken on 1.21 for some reason. i'll have to look into it. I wasn't aware you were on modern- my apologies.

**Comment by Tellinq** [comment]
Now that you mention 1.8, I actually never ended up testing 1.8. I’m not sure if that was an issue originally. I can check that later to see before/after as well for consistency

**Comment by nextdayy** [comment]
should be fixed as mentioned earlier. apologies about the inconvenience.

**Comment by Tellinq** [comment]
I can confirm this is resolved now!
